### ISSUE TITLE
Consider collaborating with quicktype

### ISSUE THREAD

**Issue by dvdsgl** [Jugale/json2swift#1]
👋 Hey! Nice work!

I've been working on the same problem in http://github.com/quicktype/quicktype for 9 months now. You can try it out at https://app.quicktype.io?lang=swift . Perhaps you'd like to collaborate with us on this project?

**Comment by maxchuquimia** [comment]
Hey, that looks great! I built my own not only for use but for also so I could learn more Javascript.
If I have some time and think of an idea I'll make a pull request 😊
For the moment, feel free to take whatever you like from this project 👍
